name: Minimal CI

on:
  push:
    branches: [ main ]

jobs:
  basic-check:
    name: Basic Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Check files
      run: |
        echo "=== Repository structure ==="
        ls -la
        echo ""
        echo "=== Source files ==="
        find src -name "*.ts" | head -10
        echo ""
        echo "=== Successfully checked out code ==="