name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build project
      run: npm run build
    
    - name: Create tarball
      run: |
        tar -czf manic-miners-level-indexer-${{ github.ref_name }}.tar.gz \
          dist/ \
          package.json \
          package-lock.json \
          README.md \
          LICENSE \
          config.template.json
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: manic-miners-level-indexer-${{ github.ref_name }}.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false