name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quick-check:
    name: Quick Type and Lint Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install minimal dependencies
      run: |
        npm install --no-save typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint prettier
      timeout-minutes: 5
    
    - name: Run TypeScript compiler check
      run: npx tsc --noEmit
    
    - name: Run basic ESLint check
      run: npx eslint src --ext .ts --max-warnings 0
      continue-on-error: true